steps:
# Deploy invoices function
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    cp config/config.py functions/consume-invoices
    cp config/pathnames.json functions/consume-invoices
    gcloud functions deploy ${PROJECT_ID}-consume-invoices-func \
    --entry-point=topic_to_xml \
    --runtime=python37 \
    --trigger-http \
    --project=${PROJECT_ID} \
    --region=europe-west1 \
    --max-instances=10 \
    --set-env-vars=PUBSUB_VERIFICATION_TOKEN=00000aaaa
